name: Run

on:
  workflow_dispatch:
  schedule:
    - cron: "45 * * * *"

jobs:
  risingskulls:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: mskelton/setup-yarn@v1

      - run: yarn ts-node ./checkListings.ts
        env:
          CONTRACT_ADDRESS: ""
          COLLECTION_SLUG: rising-skulls
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_CHANNEL_ID: "899725100205608981"
